### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by Jayesh-Cldscle** [Centurix/Pantastic#2]
After running the command "python pantastic.py --dir test", it is not able to write output file

Traceback (most recent call last):
  File "/Users/jayeshdesai/work-dirs/pci-pal/Pantastic/pantastic.py", line 114, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/jayeshdesai/work-dirs/pci-pal/Pantastic/.venv/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayeshdesai/work-dirs/pci-pal/Pantastic/.venv/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/jayeshdesai/work-dirs/pci-pal/Pantastic/.venv/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayeshdesai/work-dirs/pci-pal/Pantastic/.venv/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayeshdesai/work-dirs/pci-pal/Pantastic/pantastic.py", line 108, in main
    pan_manager.scan_file_with_output(file)
  File "/Users/jayeshdesai/work-dirs/pci-pal/Pantastic/pantastic/pantastic.py", line 64, in scan_file_with_output
    self.output_handle = open(self.output, 'w')
                         ^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType

Can someone please help me here?

**Comment by Centurix** [comment]
Hi, I recently did a quick upgrade from the older Python 2.x codebase to Python 3.

I've pushed some changes to address the file handling issue here and processing files better. Could pull master and give it another try?

Thanks!

**Comment by Jayesh-Cldscle** [comment]
> Hi, I recently did a quick upgrade from the older Python 2.x codebase to Python 3.
> 
> I've pushed some changes to address the file handling issue here and processing files better. Could pull master and give it another try?
> 
> Thanks!

Worked, Thank you so much!!

**Comment by Centurix** [comment]
no problems, best of luck with the PCI audits!
